name: gh-deployment-workflow

run-name: GitHub Actions 🚀 is run  ${{github.actor}}

on:
  push:
    branches: ["main"]
    paths:
      - "index.html"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: gh-deployment-workflow
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: gihub-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        env:
            ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
        uses: actions/deploy-pages@v4
